Repository jellehuibregtse/vertex-cover, pull requests merged in 2021-04, with the labels that each got.

#6 Update README.md (closes #3)
  .idea/inspectionProfiles/Project_Default.xml
  .idea/modules.xml
  .idea/vcs.xml
  .idea/vertex-cover.iml
  README.md
Labels: documentation

#8 Connect backend to frontend
  graph.py
  main.py
  src/App.css
  src/App.tsx
Labels: enhancement

#9 Improve visualisation
  src/App.css
  src/App.tsx
  src/Util/useWindowDimensions.tsx
  src/index.css
Labels: enhancement

#12 Feature/vertex-cover
  .idea/misc.xml
  .idea/vertex-cover.iml
  graph.py
  main.py
  src/App.css
  src/App.tsx
  src/NavBar/NavBar.tsx
  src/Util/convertToD3Graph.tsx
  src/Util/useWindowDimensions.tsx
  src/index.css
  yarn.lock
Labels: enhancement

#14 Make graph center on resize
  src/App.css
  src/App.tsx
  src/Components/Clock.tsx
  src/Components/Popup.tsx
  src/NavBar/NavBar.tsx
  src/Util/convertToD3Graph.tsx
  src/Util/getTimeNow.tsx
  src/Util/useWindowDimensions.tsx
Labels: bug, enhancement

#15 Rearrange repository
  .github/workflows/build-client.yml
  .github/workflows/build-server.yml
  .github/workflows/deploy-client.yml
  .github/workflows/deploy-server.yml
  .gitignore
  .idea/vertex-cover.iml
  __pycache__/test_main.cpython-37-pytest-6.2.3.pyc
  client/.gitignore
  client/Dockerfile
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/public/manifest.json
  client/public/robots.txt
  client/src/App.css
  client/src/App.tsx
  client/src/Components/Clock.tsx
  client/src/Components/Popup.tsx
  client/src/NavBar/NavBar.tsx
  client/src/Util/convertToD3Graph.tsx
  client/src/Util/getTimeNow.tsx
  client/src/Util/useWindowDimensions.tsx
  client/src/index.css
  client/src/index.tsx
  client/src/react-app-env.d.ts
  client/src/reportWebVitals.ts
  client/src/setupTests.ts
  client/tsconfig.json
  client/yarn.lock
  server/.gitignore
  server/Dockerfile
  server/graph.py
  server/main.py
  server/requirements.txt
  server/test_main.py
  src/App.test.tsx
Labels: enhancement

#21 Kernelization
  client/.env.development
  client/src/App.tsx
  client/src/Util/convertToD3Graph.tsx
  client/yarn.lock
  server/graph.py
  server/main.py
Labels: enhancement

#23 Rearrange code
  client/src/App.tsx
  client/src/Components/CodeViewer.tsx
  client/src/Components/SideBar.tsx
  client/src/Interfaces/PromiseWithCancel.ts
Labels: enhancement
